### ISSUE TITLE
Login mit reiner Benutzernummer funktioniert nicht

### ISSUE THREAD

**Issue by woiv1011** [denwehrle/kitbib-android#1]
Wenn ich versuche mich mit meiner Benutzernummer anzumelden, kommt der Fehler "Ungültiger Alias".
In LoginActivity.java, Zeile 169 wird in isEmailValid() abgefragt, ob der String mit '@' beginnt, das ist aber nur bei Verwendung des Alias korrekt.
Mein Account als externer Bibliotheksnutzer hat keinen Alias, deswegen ist das keine Option.

**Comment by denwehrle** [comment]
Hi @woiv1011, danke nochmal für deine Nachricht! Mit https://github.com/denwehrle/kitbib-android/commit/a466261c6a21be94dcc2f7a55217a4d815da926b sowie Version 1.3.1 ist der check entfernt und ein Login ist auch über die Benutzernummer möglich!

Lg

**Comment by woiv1011** [comment]
Danke für das Update !
Es funktioniert jetzt auch bei mir auf dem Handy :)

MfG

Am So., 14. Juli 2019 um 14:44 Uhr schrieb Dennis Wehrle <
notifications@github.com>:
